C:\VulkanSDK\1.3.261.1\Bin\glslc.exe sky.comp -o sky.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe gradient.comp -o gradient.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe gradient_color.comp -o gradient_color.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe colored_triangle.frag -o colored_triangle.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe colored_triangle_mesh.vert -o colored_triangle_mesh.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe tex_image.frag -o tex_image.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe pbr_cluster.vert -o pbr_cluster.vert.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe pbr_cluster.frag -o pbr_cluster.frag.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe skybox.vert -o skybox.vert.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe skybox.frag -o skybox.frag.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe cascaded_shadows.vert -o cascaded_shadows.vert.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe cascaded_shadows.frag -o cascaded_shadows.frag.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe cascaded_shadows.geom -o cascaded_shadows.geom.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe hdr.vert -o hdr.vert.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe hdr.frag -o hdr.frag.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe blur.vert -o blur.vert.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe blur.frag -o blur.frag.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe depth_pass.vert -o depth_pass.vert.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe filter_cube.vert -o filter_cube.vert.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe irradiance_cube.frag -o irradiance_cube.frag.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe irradiance_cube.comp -o irradiance_cube.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe brdf_lut.comp -o brdf_lut.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe pre_filter.comp -o pre_filter.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe pre_filter_envmap.frag -o pre_filter_envmap.frag.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe gen_brdf_lut.vert -o gen_brdf_lut.vert.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe gen_brdf_lut.frag -o gen_brdf_lut.frag.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe pre_filter_envmap.frag -o pre_filter_envmap.frag.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe cluster_shader.comp -o cluster_shader.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe cluster_cull_light_shader.comp -o cluster_cull_light_shader.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe pbr_bindless.vert -o pbr_bindless.vert.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe pbr_bindless.frag -o pbr_bindless.frag.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe indirect_cull.comp -o indirect_cull.comp.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe depth_reduce.comp -o depth_reduce.comp.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe indirect_forward.vert -o indirect_forward.vert.spv
C:\VulkanSDK\1.3.261.1\Bin\glslc.exe indirect_forward.frag -o indirect_forward.frag.spv 
pause